//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaPatcherCLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaPatcherCLI.LocalizedText - Copy", typeof(LocalizedText___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATCHING:.
        /// </summary>
        internal static string ApplyPatch1 {
            get {
                return ResourceManager.GetString("ApplyPatch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Game file:.
        /// </summary>
        internal static string ApplyPatch2 {
            get {
                return ResourceManager.GetString("ApplyPatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Patch script:.
        /// </summary>
        internal static string ApplyPatch3 {
            get {
                return ResourceManager.GetString("ApplyPatch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game file not found:.
        /// </summary>
        internal static string ApplyPatch4 {
            get {
                return ResourceManager.GetString("ApplyPatch4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch script not found:.
        /// </summary>
        internal static string ApplyPatch5 {
            get {
                return ResourceManager.GetString("ApplyPatch5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Reading data.win....
        /// </summary>
        internal static string ApplyPatch6 {
            get {
                return ResourceManager.GetString("ApplyPatch6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Using the script....
        /// </summary>
        internal static string ApplyPatch7 {
            get {
                return ResourceManager.GetString("ApplyPatch7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Saving changes....
        /// </summary>
        internal static string ApplyPatch8 {
            get {
                return ResourceManager.GetString("ApplyPatch8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully passed!.
        /// </summary>
        internal static string ApplyPatch9 {
            get {
                return ResourceManager.GetString("ApplyPatch9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! ERROR WHILE PATCHING.
        /// </summary>
        internal static string ApplyPatchError1 {
            get {
                return ResourceManager.GetString("ApplyPatchError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRITICAL ERROR:.
        /// </summary>
        internal static string CriticalError1 {
            get {
                return ResourceManager.GetString("CriticalError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details and installer log are saved to the file:.
        /// </summary>
        internal static string ErrorLog1 {
            get {
                return ResourceManager.GetString("ErrorLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write installer log to file.
        /// </summary>
        internal static string ErrorLog2 {
            get {
                return ResourceManager.GetString("ErrorLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (press any key to terminate the program).
        /// </summary>
        internal static string ErrorLog3 {
            get {
                return ResourceManager.GetString("ErrorLog3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception:.
        /// </summary>
        internal static string InnerException1 {
            get {
                return ResourceManager.GetString("InnerException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patch has been applied successfully!.
        /// </summary>
        internal static string PatchSuccess1 {
            get {
                return ResourceManager.GetString("PatchSuccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can launch the game translated game.
        /// </summary>
        internal static string PatchSuccess2 {
            get {
                return ResourceManager.GetString("PatchSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patch could not be applied due to path errors..
        /// </summary>
        internal static string PathError1 {
            get {
                return ResourceManager.GetString("PathError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning - unable to check for (or remove) the \&quot;Read-only\&quot; attribute on the file.
        /// </summary>
        internal static string ReadonlyWarning1 {
            get {
                return ResourceManager.GetString("ReadonlyWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script error:.
        /// </summary>
        internal static string ScriptError1 {
            get {
                return ResourceManager.GetString("ScriptError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Usage1 {
            get {
                return ResourceManager.GetString("Usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeltarunePatcherCLI.exe --game \&quot;path_to_the_game\&quot; --scripts \&quot;path_to_scripts\&quot;.
        /// </summary>
        internal static string Usage2 {
            get {
                return ResourceManager.GetString("Usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:.
        /// </summary>
        internal static string Usage3 {
            get {
                return ResourceManager.GetString("Usage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking paths....
        /// </summary>
        internal static string ValidatePath1 {
            get {
                return ResourceManager.GetString("ValidatePath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Game folder:.
        /// </summary>
        internal static string ValidatePath2 {
            get {
                return ResourceManager.GetString("ValidatePath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Scripts folder:.
        /// </summary>
        internal static string ValidatePath3 {
            get {
                return ResourceManager.GetString("ValidatePath3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Game folder not found.
        /// </summary>
        internal static string ValidatePath4 {
            get {
                return ResourceManager.GetString("ValidatePath4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Script folder not found.
        /// </summary>
        internal static string ValidatePath5 {
            get {
                return ResourceManager.GetString("ValidatePath5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: DELTARUNE.exe not found.
        /// </summary>
        internal static string ValidatePath6 {
            get {
                return ResourceManager.GetString("ValidatePath6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All paths are correct.
        /// </summary>
        internal static string ValidatePath7 {
            get {
                return ResourceManager.GetString("ValidatePath7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking paths:.
        /// </summary>
        internal static string ValidatePath8 {
            get {
                return ResourceManager.GetString("ValidatePath8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string Warning1 {
            get {
                return ResourceManager.GetString("Warning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELTARUNE Translation Patcher CLI.
        /// </summary>
        internal static string Welcome1 {
            get {
                return ResourceManager.GetString("Welcome1", resourceCulture);
            }
        }
    }
}
